#!/usr/bin/env python

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from scipy.interpolate import griddata
import sys

av = sys.argv

if len(av) < 2 or av[1] == '-h':
    sys.stderr.write('''usage: {:} DAT
Contour plot of scalar field u defined in points x,y.
DAT: path to ASCII file with lines: x y u
# Output:
# DAT.png in current folder
'''.format(av[0]))
    exit(1)

p = av[1]

x,y,u = np.loadtxt(p).T

fig,ax = plt.subplots(figsize=(1.,1.))
ax.axes.get_xaxis().set_visible(False)
ax.axes.get_yaxis().set_visible(False)
ax.set_frame_on(False)

nx = 128
ny = nx

x1 = np.linspace(0., 1., nx)
y1 = np.linspace(0., 1., ny)

xg,yg = np.meshgrid(x1, y1)

ug = griddata((x, y), u, (xg, yg), method='nearest')

ax.imshow(np.flipud(ug), vmin=0, vmax=1)

fo = "{:}.png".format(p)
print(fo)

plt.savefig(fo, dpi=2000, bbox_inches='tight',pad_inches=0)
