#!/usr/bin/env python

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from scipy.interpolate import griddata
import sys
import os

av = sys.argv

if len(av) < 2 or av[1] == '-h':
    sys.stderr.write('''usage: {:} DAT
Contour plot of scalar field u defined in points x,y.
DAT: path to ASCII file with lines: x y u
# Output:
# DAT.png in current folder
'''.format(av[0]))
    exit(1)

p = av[1]

# grid size
nx = 512
ny = nx
x1 = np.linspace(0., 1., nx)
y1 = np.linspace(0., 1., ny)
xg,yg = np.meshgrid(x1, y1)

# read points
x,y,u = np.loadtxt(p).T

# resample to grid
ug = griddata((x, y), u, (xg, yg), method='nearest')

# init figure
fig = plt.figure(figsize=(1.,1.), dpi=1, frameon=False)
ax = plt.Axes(fig, [0., 0., 1., 1.])
ax.set_axis_off()
fig.add_axes(ax)

# plot
m = 1.
u = np.clip(u, -m, m)
ax.imshow(np.flipud(ug), vmin=-m, vmax=m, cmap=plt.get_cmap("coolwarm"))

# save
pb = os.path.splitext(p)[0]
fo = "{:}.png".format(pb)
print(fo)
fig.set_size_inches(1024,1024)
fig.savefig(fo, dpi=1)
