#!/usr/bin/env python

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from scipy.interpolate import griddata
import sys
import os

av = sys.argv

if len(av) < 2 or av[1] == '-h':
    sys.stderr.write('''usage: {:} DAT
Contour plot of scalar field u[x,y] on uniform grid of size (nx,ny)
DAT: path to binary file: 
     nx:uint32 ny:uint32 u[0,0]:float64 u[1,0]:float64 ...
# Output:
# DAT.png in current folder
'''.format(av[0]))
    exit(1)

p = av[1]

f = open(p)

# read grid size
nx,ny = np.fromfile(f, np.uint32, count=2)
# read field 
u = np.fromfile(f, np.float64)
u = u.reshape((nx, ny))

# init figure
fig = plt.figure(figsize=(1.,1.), dpi=1, frameon=False)
ax = plt.Axes(fig, [0., 0., 1., 1.])
ax.set_axis_off()
fig.add_axes(ax)

# plot
m = 1.
u = np.clip(u, -m, m)
ax.imshow(np.flipud(u), vmin=-m, vmax=m, cmap=plt.get_cmap("coolwarm"),
        interpolation="none")

# save
pb = os.path.splitext(p)[0]
fo = "{:}.png".format(pb)
print(fo)
fig.set_size_inches(1024,1024)
fig.savefig(fo, dpi=1)
